name: Exabuster - Build Site

on:
  push

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:

      # Install the Exabuster Dependencies
      - name: Install Exabuster Dependencies
        run: |
          pip3 install setuptools wheel
          pip3 install docopt==0.6.1 pyquery==1.2.8

      # Install the Ghost blogging platform
      - name: Install Ghost
        run: sudo npm install ghost-cli@latest -g

      # Go to a child folder
      - name: Make Working Directory
        run: mkdir TempGhostSite

      # Create a fresh ghost install
      - name: Make Executable Ghost Instance
        run: ghost install local
        working-directory: ./TempGhostSite

      # Run "ghost stop"
      - name: Stop Ghost Instance Execution (for now)
        run: ghost stop
        working-directory: ./TempGhostSite

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
        #  path: ./TempGhostRepo

      # Copy the contents of the repo into the fresh ghost install
      - name: Copy Repository Files to Working Directory
        run: cp -vR content TempGhostSite

      # Go into folder and run "ghost start"
      - name: Start Ghost Server
        run: ghost start
        working-directory: ./TempGhostSite

      # Go to parent folder and run Exabuster
      - name: Generate Static Site with Exabuster
        run: python3 exabuster.py generate --domain=localhost:2368 --new-domain=zalo.github.io/Exabuster

      # Deploy to local repo
      - name: Push artifacts to the gh-pages branch
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: static
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload the results
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Ghost Blog
          path: static

      # Run "ghost stop"
      - name: Stop Ghost Instance Execution to Upload Logs
        if: ${{ always() }}
        run: ghost stop
        working-directory: ./TempGhostSite

      # Upload the results
      - name: Upload Ghost Logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Ghost Logs
          path: TempGhostSite/content/logs