name: Exabuster - Build Site

on:
  push

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true
        #  path: ./TempGhostRepo

      # Attempt to Load Node Module Cache
      - name: Cache Node Modules
        id: cache-node
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-

      # Attempt to Load Pip Package Cache
      - name: Cache Pip Packages
        id: cache-pip
        uses: actions/cache@v2
        env:
          cache-name: cache-pip-packages
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit
          key: ${{ runner.os }}-pip-${{ env.cache-name }}-

      # Attempt to Load Ghost CMS Cache
      - name: Cache Ghost Install
        id: cache-ghost
        uses: actions/cache@v2
        env:
          cache-name: cache-ghost-cms
        with:
          path: ./TempGhostSite
          # Look to see if there is a cache hit
          key: ${{ runner.os }}-ghost-${{ env.cache-name }}-

      # Install the Exabuster Dependencies
      - name: Install Exabuster Dependencies
        #if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          pip3 install setuptools wheel
          pip3 install docopt==0.6.1 pyquery==1.2.8

      # Install the Ghost blogging platform
      - name: Install Ghost
        #if: steps.cache-node.outputs.cache-hit != 'true'
        run: sudo npm install ghost-cli@latest -g

      # Go to a child folder
      - name: Make Working Directory
        if: steps.cache-ghost.outputs.cache-hit != 'true'
        run: mkdir TempGhostSite

      # Create a fresh ghost install
      - name: Make Executable Ghost Instance and Start
        if: steps.cache-ghost.outputs.cache-hit != 'true'
        run: ghost install local
        working-directory: ./TempGhostSite

      # Run "ghost stop"
      - name: Stop Ghost Instance to Copy Content
        run: ghost stop
        working-directory: ./TempGhostSite

      # Debug
      #- name: Debug Print Files
      #  run: |
      #    ls
      #    ls TempGhostSite

      # Copy the contents of the repo into the fresh ghost install
      - name: Copy Repository Files to Working Directory
        run: cp -vR content TempGhostSite

      # Go into folder and run "ghost start"
      - name: Start Ghost Instance
        run: ghost start
        working-directory: ./TempGhostSite

      # Go to parent folder and run Exabuster
      - name: Generate Static Site with Exabuster
        run: python3 exabuster.py generate --domain=http://localhost:2368 --new-domain=https://zalo.github.io/Exabuster

      # Deploy to local repo
      - name: Push artifacts to the gh-pages branch
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: static
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run "ghost stop"
      - name: Stop Ghost Instance to Upload Logs
        if: ${{ always() }}
        run: ghost stop
        working-directory: ./TempGhostSite

      # Upload the log results in-case there's an error
      - name: Upload Ghost Logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Ghost Logs
          path: TempGhostSite/content/logs
